#!/bin/bash
# Find the directory of the executable using $(dirname $0), convert it to absolute path using
# realpath, and use it to find build directory (e.g., .../build/Debug or /app/).
export BUILD_ROOT=$(realpath $(dirname $0)/../..)


source ${BUILD_ROOT}/src/cmake_utils/gen_solidity_venv/bin/activate
 CMAKE_TARGET_NAME=gen_solidity_exe ${BUILD_ROOT}/src/cmake_utils/gen_solidity_venv/bin/python -u -m gen_solidity_env  "$@"
