SET (DEPENDENCIES
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/alloc.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/bitwise.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/bool.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/cairo_builtins.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/dict_access.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/ec_point.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/hash.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/math.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/math_cmp.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/memcpy.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/pow.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/registers.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/common/uint256.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/cairo/lang/compiler/lib/registers.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/starknet/common/storage.cairo
/app/build/Release/python_pip/python3.7/pip_cairo_lang/starkware/starknet/common/syscalls.cairo
/app/src/starkware/starknet/std_contracts/ERC20/ERC20.cairo
/app/src/starkware/starknet/std_contracts/ERC20/ERC20_base.cairo
/app/src/starkware/starknet/std_contracts/ERC20/permitted.cairo
/app/src/starkware/starknet/std_contracts/upgradability_proxy/initializable.cairo
)
